### Practical No. 4 Implement a Naive Bayes Classifier and Evaluate the Performance

Submitted By: Shantanu Yadav     
Roll No.: 75

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('plant_growth_data.csv')
df

,Soil_Type,Sunlight_Hours,Water_Frequency,Fertilizer_Type,Temperature,Humidity,Growth_Milestone
0,loam,5.192294,bi-weekly,chemical,31.719602,61.591861,0
1,sandy,4.033133,weekly,organic,28.919484,52.422276,1
2,loam,8.892769,bi-weekly,none,23.179059,44.660539,0
3,loam,8.241144,bi-weekly,none,18.465886,46.433227,0
4,sandy,8.374043,bi-weekly,organic,18.128741,63.625923,0
...,...,...,...,...,...,...,...
188,sandy,5.652000,daily,none,28.000000,70.200000,0
189,clay,7.528000,weekly,chemical,30.500000,60.100000,1
190,loam,4.934000,bi-weekly,none,24.500000,61.700000,0
191,sandy,8.273000,daily,organic,27.900000,69.500000,1
192,clay,6.732000,weekly,none,21.700000,56.900000,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Soil_Type         193 non-null    object
 1   Sunlight_Hours    193 non-null    float64
 2   Water_Frequency   193 non-null    object
 3   Fertilizer_Type   193 non-null    object
 4   Temperature       193 non-null    float64
 5   Humidity          193 non-null    float64
 6   Growth_Milestone  193 non-null    int64
dtypes: float64(3), int64(1), object(3)
memory usage: 10.7+ KB

In [4]:
df.shape

(193, 7)

In [5]:
df.describe()

       Sunlight_Hours  Temperature    Humidity  Growth_Milestone
count      193.000000   193.000000  193.000000        193.000000
mean         6.826484    25.076087   58.098927          0.497409
std          1.599509     5.354170   12.631799          0.501294
min          4.033133    15.200000   30.567682          0.000000
25%          5.477000    20.637095   49.300000          0.000000
50%          6.833290    25.912336   59.182806          0.000000
75%          8.241144    29.757938   69.100000          1.000000
max          9.913903    34.810103   79.648240          1.000000

In [6]:
df.isnull().sum()

Soil_Type           0
Sunlight_Hours      0
Water_Frequency     0
Fertilizer_Type     0
Temperature         0
Humidity            0
Growth_Milestone    0
dtype: int64

In [7]:
df.columns

Index(['Soil_Type', 'Sunlight_Hours', 'Water_Frequency', 'Fertilizer_Type',
       'Temperature', 'Humidity', 'Growth_Milestone'],
      dtype='object')

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Soil_Type'] = le.fit_transform(df['Soil_Type'])
df['Water_Frequency'] = le.fit_transform(df['Water_Frequency'])
df['Fertilizer_Type'] = le.fit_transform(df['Fertilizer_Type'])

In [9]:
X = df.drop(columns = ['Growth_Milestone'],axis = 1)
y = df['Growth_Milestone']

In [12]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,f1_score
from sklearn.neighbors import KNeighborsClassifier

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)

In [13]:
models = {
    "KNN":KNeighborsClassifier(),
    "Naive Bayes":GaussianNB(),
}

In [14]:
results = []

In [15]:
for name,model in models.items():
    model.fit(x_train_scaled,y_train)
    y_pred = model.predict(x_test_scaled)
    acc = accuracy_score(y_test,y_pred)
    f1 = f1_score(y_test,y_pred)
    cm = confusion_matrix(y_test, y_pred)
    results.append({
        'model':name,
        'accuracy':round(acc,4),
        'f1 score':round(f1,4),
'confusion matrix': cm
    })

In [16]:
results

[{'model': 'KNN',
  'accuracy': 0.4872,
  'f1 score': 0.4737,
  'confusion matrix': array([[10, 10],
         [10,  9]])},
 {'model': 'Naive Bayes',
  'accuracy': 0.4872,
  'f1 score': 0.5,
  'confusion matrix': array([[ 9, 11],
         [ 9, 10]])}]